package co.fallsoft.pocket

import java.util.Locale

/** Authored, offline learning vocabulary. Match whole labels; never rewrite executable syntax. */
object ImmersionLexicon {
    val common=mapOf(
        "Approve once" to "Approva una volta",
        "Clear all saved speech" to "Svuota tutte le letture salvate",
        "Reload backends" to "Ricarica i motori",
        "Use Codex" to "Usa Codex",
        "Close image" to "Chiudi l’immagine",
        "New team task" to "Nuovo incarico al gruppo",
        "Task name" to "Nome dell’incarico",
        "What should the team do?" to "Che cosa deve fare il gruppo?",
        "Retry saved task" to "Riprova l’incarico salvato",
        "Send answer" to "Invia la risposta",
        "Retry saved answer" to "Riprova la risposta salvata",
        "No pending requests" to "Nessuna richiesta in attesa",
        "Automatic language cycling" to "Alternanza automatica delle lingue",
        "Reduced motion · cycling without animation" to "Movimento ridotto · alternanza senza animazione",
        "How much Italian?" to "Quanto italiano?",
        "Gradual" to "Graduale",
        "Balanced" to "Bilanciato",
        "Intense" to "Intenso",
        "Open request" to "Apri la richiesta",
        "Waiting for fresh usage" to "In attesa dei dati di utilizzo aggiornati",
        "Important" to "In evidenza",
        "All" to "Tutti",
        "Clear" to "Svuota",
        "Remove" to "Rimuovi",
        "Unsave" to "Rimuovi dai salvati",
        "Voice setup" to "Impostazioni vocali",
        "App settings" to "Impostazioni dell’app",
        "Backend" to "Motore",
        "Queue message" to "Metti il messaggio in coda",
        "Open source conversation" to "Apri la conversazione di origine",
        "Needs you" to "Serve il tuo intervento",
        "Your turn" to "Tocca a te",
        "Starting" to "Avvio",
        "Loading" to "Caricamento",
        "Checking" to "Verifica in corso",
        "Stopped" to "Interrotto",
        "Shown in conversation above" to "Mostrato nella conversazione qui sopra",
        "Room" to "Gruppo",
        "Direct" to "Diretto",
        "Full access" to "Accesso completo",
        "Earlier messages" to "Messaggi precedenti",
        "Reload conversation" to "Ricarica la conversazione",
        "Connect Codex" to "Collega Codex",
        "Review" to "Esamina",
        "Later · 30m" to "Più tardi · 30 min",
        "Connect Codex on this phone" to "Collega Codex su questo telefono",
        "Reconnect now" to "Riconnetti ora",
        "Send a test notification" to "Invia una notifica di prova",
        "Notification settings" to "Impostazioni delle notifiche",
        "Disconnect this phone" to "Scollega questo telefono",
        "Enable NextComp in Accessibility" to "Abilita NextComp nelle impostazioni di accessibilità",
        "Speak messages" to "Leggi i messaggi ad alta voce",
        "Your answer" to "La tua risposta",
        "Loading history…" to "Caricamento della cronologia…",
        "Talk to Codex" to "Parla con Codex",
        "Answer pending question" to "Rispondi alla domanda in attesa",
        "Keep latest reply in notes" to "Conserva l’ultima risposta nelle note",
        "Model, effort & mode" to "Modello, impegno e modalità",
        "Saved answer" to "Risposta salvata",
        "Retained passage · source outside loaded history" to "Passaggio conservato · origine fuori dalla cronologia caricata",
        "Spoken update ·" to "Aggiornamento vocale ·",
        "Surrounding conversation" to "Contesto della conversazione",
        "No important updates yet" to "Ancora nessun aggiornamento in evidenza",
        "Edit" to "Modifica",
        "Latest" to "Ultimi",
        "Queued messages" to "Messaggi in coda",
        "Resume queue" to "Riprendi la coda",
        "Archive conversation?" to "Archiviare la conversazione?",
        "Send this message again?" to "Inviare di nuovo questo messaggio?",
        "Retry anyway" to "Riprova comunque",
        "Edit message" to "Modifica il messaggio",
        "Next-turn controls" to "Controlli per il prossimo turno",
        "Message the team" to "Scrivi al gruppo",
        "Submitting…" to "Invio in corso…",
        "Retry saved command" to "Riprova il comando salvato",
        "Check connection" to "Verifica la connessione",
        "Retry now" to "Riprova ora",
        "Codex offline" to "Codex non connesso",
        "Starting…" to "Avvio…",
        "Check task status" to "Verifica lo stato dell’attività",
        "Start task" to "Avvia l’attività",
        "Unfollow" to "Smetti di seguire",
        "Loading…" to "Caricamento…",
        "Load earlier activity" to "Carica attività precedenti",
        "Steer this task…" to "Orienta questa attività…",
        "Steer now" to "Orienta ora",
        "Send now" to "Invia ora",
        "Plan mode" to "Modalità pianificazione",
        "Build mode" to "Modalità esecuzione",
        "Tones" to "Suoni",
        "Labels" to "Etichette",
        "System" to "Sistema",
        "Finished" to "Completato",
        "Question" to "Domanda",
        "Problem" to "Problema",
        "▶ Finished" to "▶ Completato",
        "▶ Question" to "▶ Domanda",
        "▶ Problem" to "▶ Problema",
        "Clear saved speech" to "Svuota la voce salvata",
        "Activity" to "Attività", "Hide controls" to "Nascondi controlli", "Controls & usage" to "Controlli e utilizzo",
        "Message Codex…" to "Scrivi a Codex…", "Sending…" to "Invio in corso…",
        "English support" to "Supporto in inglese", "Message coordinator" to "Scrivi al coordinatore",
        "New task" to "Nuova attività", "Show sessions" to "Mostra sessioni", "Find sessions" to "Cerca sessioni",
        "Recent" to "Recenti", "Following" to "Seguiti", "Archived" to "Archiviati", "Allow once" to "Consenti una volta",
        "Decline" to "Rifiuta", "Send answers" to "Invia risposte", "Refresh" to "Aggiorna", "Load earlier messages" to "Carica messaggi precedenti",
        "Sending" to "Invio in corso", "Rename conversation" to "Rinomina conversazione", "Type your message" to "Scrivi il tuo messaggio",
        "Retry history" to "Ricarica la cronologia", "Retry saved turn" to "Riprova il messaggio salvato",
        "Work" to "Lavoro", "Mission" to "Missione", "Settings" to "Impostazioni", "Find" to "Cerca", "Talk" to "Parla",
        "Mic" to "Microfono", "Microphone" to "Microfono", "Keyboard" to "Tastiera", "Back" to "Indietro", "Stop" to "Ferma",
        "Send" to "Invia", "Send message" to "Invia messaggio", "Stop & send" to "Ferma e invia", "Stop & Send" to "Ferma e invia",
        "Record" to "Registra", "Recording" to "Registrazione", "Speaking" to "Voce in corso", "Listening" to "In ascolto",
        "Ready" to "Pronto", "Paused" to "In pausa", "Resume" to "Riprendi", "Pause" to "Pausa", "Replay" to "Riascolta",
        "Connected" to "Connesso", "Connecting" to "Connessione", "Reconnecting" to "Riconnessione", "Offline" to "Non connesso",
        "On" to "Attivo", "Off" to "Disattivo", "Notifications" to "Notifiche", "Notification" to "Notifica",
        "Queue" to "In coda", "Queued" to "In coda", "Steer" to "Orienta", "Reply" to "Rispondi", "Answer" to "Rispondi",
        "Skip" to "Salta", "Later" to "Più tardi", "Retry" to "Riprova", "Retry needed" to "Riprova", "Cancel" to "Annulla",
        "Save" to "Salva", "Close" to "Chiudi", "Done" to "Fatto", "Dismiss" to "Chiudi", "Copy" to "Copia",
        "Keep" to "Conserva", "Keep reply" to "Conserva risposta", "Rename" to "Rinomina", "Archive" to "Archivia", "Restore" to "Ripristina",
        "Model" to "Modello", "Effort" to "Impegno", "Mode" to "Modalità", "Follow" to "Segui", "New session" to "Nuova sessione",
        "New conversation" to "Nuova conversazione", "Coordinator" to "Coordinatore", "All sessions" to "Tutte le sessioni",
        "Working" to "Al lavoro", "Thinking" to "Riflessione", "Complete" to "Completato", "Completed" to "Completato", "Failed" to "Non riuscito",
        "Running a command" to "Esecuzione di un comando", "Reading a file" to "Lettura di un file", "Editing a file" to "Modifica di un file",
        "Searching" to "Ricerca", "Running tests" to "Esecuzione dei test", "Waiting for an answer" to "In attesa di una risposta",
        "Message" to "Messaggio", "Write a message" to "Scrivi un messaggio", "Ask anything" to "Chiedi qualsiasi cosa",
        "Type a message" to "Scrivi un messaggio", "Search conversations" to "Cerca conversazioni", "Search sessions" to "Cerca sessioni",
        "Volume" to "Volume", "Speech volume" to "Volume della voce", "Usage" to "Utilizzo", "Details" to "Dettagli",
        "Update" to "Aggiorna", "Updates" to "Aggiornamenti", "Check for updates" to "Cerca aggiornamenti", "Install update" to "Installa aggiornamento",
        "Full permissions" to "Permessi completi", "Workstation" to "Computer", "This phone" to "Questo telefono",
        "History" to "Cronologia", "Load earlier" to "Carica precedenti", "Open conversation" to "Apri conversazione",
        "Questions" to "Domande", "Attention" to "Attenzione", "Answers & notes" to "Risposte e note",
        "Steer running turn" to "Orienta il turno", "Project folder" to "Cartella del progetto",
        "What would you like Codex to do?" to "Che cosa vuoi far fare a Codex?",
        "Language motion" to "Transizioni di lingua", "Italian immersion" to "Immersione in italiano", "Original / Italiano" to "Originale / Italiano"
    )
    private val normalized=common.mapKeys{it.key.lowercase(Locale.ROOT)}
    fun italian(text:String):String?=normalized[text.trim().lowercase(Locale.ROOT)]
}
