import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import express from 'express';
import {AppUpdates,mountAppUpdates} from '../server/app-updates.mjs';
const signer='a'.repeat(64),other='b'.repeat(64),unknown='c'.repeat(64);
function setup(t){
 const dir=mkdtempSync(resolve(tmpdir(),'nextcomp-updates-')),root=resolve(dir,'app-updates');mkdirSync(root);
 const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE devices(id TEXT PRIMARY KEY);CREATE TABLE notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,thread_id TEXT,title TEXT,body TEXT,kind TEXT,attachments TEXT,created_at INTEGER);CREATE TABLE push_tokens(device_id TEXT PRIMARY KEY,project_id TEXT);CREATE TABLE push_deliveries(notification_id INTEGER,device_id TEXT,state TEXT,updated_at INTEGER,PRIMARY KEY(notification_id,device_id));INSERT INTO devices VALUES('phone'),('phone2');INSERT INTO push_tokens VALUES('phone','test'),('phone2','other-project');`);
 const push={enabled:true,config:{projectId:'test'},calls:0,async flush(){this.calls++;}},updates=new AppUpdates({dir,db,push});
 const variants=[signer,other].map((s,i)=>{const bytes=Buffer.from('apk-'+i),path='build-'+i+'.apk';writeFileSync(resolve(root,path),bytes);return {signerSha256:s,path,sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length};});
 const manifest={versionCode:25,versionName:'0.5.0-alpha.12',packageName:'co.fallsoft.pocket',variants};const save=()=>writeFileSync(resolve(root,'manifest.json'),JSON.stringify(manifest));save();
 t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});return {dir,root,db,push,updates,manifest,save};
}
test('matching installed signer receives only its own variant and newer version',t=>{const {updates}=setup(t);const m=updates.metadata(signer,'24');assert.equal(m.available,true);assert.equal(m.signerSha256,signer);assert.equal(m.versionCode,25);assert.equal(m.apkUrl,'/api/app/update/apk');assert.ok(!('path' in m));assert.ok(!('file' in m));assert.deepEqual(updates.metadata(signer,'25'),{available:false});assert.deepEqual(updates.metadata(signer,'26'),{available:false});assert.deepEqual(updates.metadata(unknown,'24'),{available:false,reason:'unsupported_signer'});assert.notEqual(updates.metadata(other,'24').sha256,m.sha256);});
test('missing manifest is safely unavailable',t=>{const {root,updates}=setup(t);rmSync(resolve(root,'manifest.json'));assert.deepEqual(updates.metadata(signer,'24'),{available:false,reason:'not_published'});});
test('malformed signer or version queries cannot select an artifact',t=>{const {updates}=setup(t);for(const s of ['',null,[signer],signer.toUpperCase(),'../release.apk'])assert.throws(()=>updates.metadata(s,'24'),{status:400});for(const v of ['',null,[],['24'],'-1','24.2','Infinity','99999999999999'])assert.throws(()=>updates.metadata(signer,v),{status:400});});
test('checksum and size must match before advertising or downloading',t=>{const {updates,root,manifest,save}=setup(t);writeFileSync(resolve(root,manifest.variants[0].path),'wrong');assert.throws(()=>updates.artifact(signer),/checksum/);manifest.variants[0].size=1;save();assert.throws(()=>updates.metadata(signer,'24'),/size/);});
test('relative traversal, absolute paths and symlink escapes are refused',t=>{const {updates,root,dir,manifest,save}=setup(t);writeFileSync(resolve(dir,'escape.apk'),'apk-0');manifest.variants[0].path='../escape.apk';save();assert.throws(()=>updates.artifact(signer),/inside/);manifest.variants[0].path=resolve(dir,'escape.apk');save();assert.throws(()=>updates.artifact(signer),/variant/);symlinkSync(resolve(dir,'escape.apk'),resolve(root,'escape.apk'));manifest.variants[0].path='escape.apk';save();assert.throws(()=>updates.artifact(signer),/inside/);});
test('invalid package or duplicate signer manifest is refused',t=>{const {updates,manifest,save}=setup(t);manifest.packageName='another.app';save();assert.throws(()=>updates.artifact(signer),/manifest/);manifest.packageName='co.fallsoft.pocket';manifest.variants[1].signerSha256=signer;save();assert.throws(()=>updates.artifact(signer),/variant/);});
test('push announcement persists once per build and paired device, including newly registered devices',async t=>{const {updates,db,push}=setup(t);assert.equal((await updates.announce()).announced,1);assert.equal((await updates.announce()).announced,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM notifications').get().n,1);assert.equal(db.prepare('SELECT kind FROM notifications').get().kind,'app_update');assert.equal(db.prepare('SELECT COUNT(*) n FROM push_deliveries').get().n,1);db.prepare("UPDATE push_tokens SET project_id='test' WHERE device_id='phone2'").run();assert.equal((await updates.announce()).announced,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM push_deliveries').get().n,2);assert.equal(push.calls,3);});
test('unconfigured push and corrupt artifact never announce',async t=>{const {updates,push,db,root,manifest}=setup(t);push.enabled=false;assert.deepEqual(await updates.announce(),{announced:0,pushEnabled:false});assert.equal(db.prepare('SELECT COUNT(*) n FROM notifications').get().n,0);push.enabled=true;writeFileSync(resolve(root,manifest.variants[0].path),'bad');await assert.rejects(updates.announce(),/size/);assert.equal(db.prepare('SELECT COUNT(*) n FROM notifications').get().n,0);});
test('HTTP routes require paired authentication, owner-only announce and matching signer download',async t=>{const {updates}=setup(t),app=express();app.use('/api',(req,res,next)=>{const token=req.headers.authorization;if(!['Bearer paired','Bearer owner'].includes(token))return res.status(401).end();req.device={id:token==='Bearer owner'?'owner':'phone'};next();});const owner=(req,res,next)=>req.device.id==='owner'?next():res.status(403).end(),route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);mountAppUpdates(app,{updates,owner,route});app.use((e,_req,res,_next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port,path='/api/app/update?signer='+signer+'&versionCode=24';assert.equal((await fetch(base+path)).status,401);assert.equal((await fetch(base+'/api/app/update/apk?signer='+signer)).status,401);const headers={Authorization:'Bearer paired'};assert.equal((await fetch(base+path,{headers})).status,200);const apk=await fetch(base+'/api/app/update/apk?signer='+signer,{headers});assert.equal(apk.status,200);assert.equal(await apk.text(),'apk-0');assert.equal((await fetch(base+'/api/app/update/apk?signer='+unknown,{headers})).status,404);assert.equal((await fetch(base+'/api/app/update/announce',{method:'POST',headers})).status,403);assert.equal((await fetch(base+'/api/app/update/announce',{method:'POST',headers:{Authorization:'Bearer owner'}})).status,200);});
test('broken manifests and missing artifacts return sanitized errors without local paths',t=>{const {updates,root,manifest,save}=setup(t);writeFileSync(resolve(root,'manifest.json'),'{bad');assert.throws(()=>updates.metadata(signer,'24'),{status:400,message:'Invalid app update manifest.'});save();rmSync(resolve(root,manifest.variants[0].path));assert.throws(()=>updates.artifact(signer),{status:503,message:'The update artifact is unavailable.'});});
