import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import http from 'node:http';
import {WebSocketServer} from 'ws';
import {randomUUID} from 'node:crypto';

const waitFor=async fn=>{for(let i=0;i<100;i++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,30));}throw Error('Condition not reached');};
test('same-thread steering, idle continuation, and exact pending request responses',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'pocket-routing-')),socket=join(dir,'codex.sock');
 const h=http.createServer(),wss=new WebSocketServer({server:h});await new Promise(r=>h.listen(socket,r));
 let peer;const calls=[],answers=[];let active=true;
 const thread=()=>({id:'thread-live',name:'Routing test',status:{type:active?'active':'idle'},turns:[{id:'turn-original',status:active?'inProgress':'completed',items:[{type:'userMessage',content:[{type:'text',text:'Please fix notification speech'}]}]}]});
 wss.on('connection',ws=>{peer=ws;ws.on('message',raw=>{const m=JSON.parse(raw);if(m.result){answers.push(m);return;}if(!m.id)return;calls.push(m);let result={};
 if(m.method==='thread/resume'||m.method==='thread/read')result={thread:thread()};
 if(m.method==='turn/steer')result={turnId:'turn-original'};
 if(m.method==='turn/start')result={turn:{id:'turn-next'}};
 if(m.method==='thread/start')result={thread:{id:'thread-phone',cwd:m.params.cwd,status:{type:'idle'},turns:[]}};
 ws.send(JSON.stringify({id:m.id,result}));
 });});
 const port=21000+Math.floor(Math.random()*1000);
 const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:String(port),POCKET_DATA:dir,CODEX_SOCKET:socket},stdio:'ignore'});
 t.after(()=>{child.kill();for(const ws of wss.clients)ws.terminate();wss.close();h.close();});
 await waitFor(async()=>{try{return (await fetch(`http://127.0.0.1:${port}/health`)).ok;}catch{return false;}});
 const {adminToken}=JSON.parse(await readFile(join(dir,'secrets.json'),'utf8'));
 const api=async(path,body)=>{const r=await fetch(`http://127.0.0.1:${port}${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${adminToken}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 await api('/api/threads/thread-live');
 const notice=await api('/api/notify',{thread_id:'thread-live',title:'Generic conversation title',message:'The update is installed.'});
 assert.equal(notice.status,200);assert.equal(notice.data.notification.spoken_text,'fix notification speech. The update is installed.');
 const modelNotice=await api('/api/notify',{thread_id:'thread-live',title:'Wrong context',message:'All tests pass.',spoken_context:'Improve spoken notifications',spoken_summary:'The fix is ready.'});
 assert.equal(modelNotice.data.notification.spoken_text,'Improve spoken notifications. The fix is ready.');
 const first=randomUUID();await api('/api/threads/thread-live/reply',{id:first,text:'Steer the same live task'});
 await waitFor(async()=>(await api('/api/threads/thread-live')).data.outgoing.find(x=>x.id===first&&x.state==='accepted'));
 assert.equal((await api(`/api/replies/${first}`)).data.state,'accepted');
 const steer=calls.find(x=>x.method==='turn/steer');assert.equal(steer.params.threadId,'thread-live');assert.equal(steer.params.expectedTurnId,'turn-original');
 active=false;const second=randomUUID();await api('/api/threads/thread-live/reply',{id:second,text:'Continue the existing idle task'});
 await waitFor(async()=>(await api('/api/threads/thread-live')).data.outgoing.find(x=>x.id===second&&x.state==='accepted'));
 assert.equal(calls.find(x=>x.method==='turn/start').params.threadId,'thread-live');
 peer.send(JSON.stringify({id:901,method:'item/commandExecution/requestApproval',params:{threadId:'thread-live',turnId:'turn-next',itemId:'command-1',command:'echo test',availableDecisions:['accept','decline']}}));
 await waitFor(async()=>(await api('/api/threads/thread-live')).data.pending.length===1);
 const approval=(await api('/api/attention')).data.notifications[0];assert.equal(approval.kind,'approval');
 assert.equal((await api(`/api/notifications/${approval.id}/attention`)).data.needsAttention,true);
 assert.equal((await api('/api/requests/901/answer',{decision:'acceptForSession'})).status,400);
 assert.equal((await api('/api/requests/901/answer',{decision:'accept'})).status,200);
 assert.equal((await api(`/api/notifications/${approval.id}/attention`)).data.needsAttention,true);
 assert.equal((await api('/api/requests/901/answer',{decision:'accept'})).status,200);
 peer.send(JSON.stringify({method:'serverRequest/resolved',params:{requestId:901}}));
 await waitFor(async()=>!(await api(`/api/notifications/${approval.id}/attention`)).data.needsAttention);
 await waitFor(()=>answers.length===1);assert.deepEqual(answers[0],{id:901,result:{decision:'accept'}});
 assert.equal((await api('/api/requests/901/answer',{decision:'accept'})).status,409);
 peer.send(JSON.stringify({id:902,method:'item/tool/requestUserInput',params:{threadId:'thread-live',questions:[{id:'choice',header:'Style',question:'Which style?'}]}}));
 await waitFor(async()=>(await api('/api/threads/thread-live')).data.pending.length===1);
 assert.equal((await api('/api/requests/902/answer',{answers:{}})).status,400);
 await api('/api/requests/902/answer',{answers:{choice:'Mint'}});await waitFor(()=>answers.length===2);
 assert.deepEqual(answers[1],{id:902,result:{answers:{choice:{answers:['Mint']}}}});
 peer.send(JSON.stringify({method:'serverRequest/resolved',params:{requestId:902}}));
 await waitFor(async()=>(await api('/api/attention')).data.notifications.length===0);
 peer.send(JSON.stringify({id:903,method:'item/tool/requestUserInput',params:{threadId:'thread-live',questions:[{id:'other',question:'Another question?'}]}}));
 await waitFor(async()=>(await api('/api/attention')).data.notifications.length===1);
 peer.send(JSON.stringify({method:'serverRequest/resolved',params:{requestId:903}}));
 await waitFor(async()=>(await api('/api/attention')).data.notifications.length===0);
 peer.send(JSON.stringify({method:'turn/completed',params:{threadId:'thread-live',turn:{status:'failed',error:{message:'Test failure requiring attention'},items:[]}}}));
 const problems=await waitFor(async()=>{const n=(await api('/api/attention')).data.notifications;return n.length===1&&n;});
 assert.equal(problems[0].kind,'error');assert.equal(problems[0].body,'Test failure requiring attention');
 peer.send(JSON.stringify({method:'turn/started',params:{threadId:'thread-live'}}));
 await waitFor(async()=>(await api('/api/attention')).data.notifications.length===0);
 peer.send(JSON.stringify({method:'turn/completed',params:{threadId:'thread-live',turn:{status:'completed',items:[]}}}));
 assert.equal((await api('/api/attention')).data.notifications.length,0);
 const request={id:randomUUID(),cwd:dir,prompt:'Start a task from the phone'};
 assert.equal((await api('/api/threads',request)).status,202);
 const started=await waitFor(async()=>{const r=(await api(`/api/session-starts/${request.id}`)).data;return r.state==='started'&&r;});
 assert.equal(started.thread_id,'thread-phone');
 await waitFor(async()=>(await api(`/api/replies/start-${request.id}`)).data.state==='accepted');
 assert.equal((await api('/api/threads',request)).data.thread_id,'thread-phone');
 assert.equal(calls.filter(c=>c.method==='thread/start').length,1);
 assert.deepEqual(calls.find(c=>c.method==='thread/start').params,{cwd:dir,sandbox:'danger-full-access',approvalPolicy:'never'});
 assert.equal(calls.findLast(c=>c.method==='turn/start').params.threadId,'thread-phone');
 active=true;assert.equal((await api('/api/threads/thread-live/interrupt',{})).status,200);
 assert.deepEqual(calls.find(c=>c.method==='turn/interrupt').params,{threadId:'thread-live',turnId:'turn-original'});
});
