import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {ImmersionWorker} from '../server/immersion-worker.mjs';
class Fake extends EventEmitter{calls=[];async connect(){}async call(method,args){this.calls.push({method,args});if(method==='account/read')return {account:{type:'chatgpt'}};if(method==='thread/start')return {thread:{id:'translator'}};if(method==='turn/start'){const sources=JSON.parse(args.input[0].text).sources;queueMicrotask(()=>{this.emit('event',{method:'item/completed',params:{threadId:'translator',item:{type:'agentMessage',text:JSON.stringify({translations:sources.map(s=>({...s,text:'Italiano '+s.text,spans:[{source:s.text,occurrence:0,target:'Italiano '+s.text,unit:'clause',note:''}]}))})}}});this.emit('event',{method:'turn/completed',params:{threadId:'translator',turn:{status:'completed'}}});});return {turn:{id:'turn'}};}}}
test('disabled mode never calls Codex; profile settings are isolated',async()=>{const codex=new Fake(),w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.submit('a',[{id:'x',text:'Hello'}]);await w.flush();assert.equal(codex.calls.length,0);w.setEnabled('b',true);assert.equal(w.snapshot('a').enabled,false);w.close();});
test('coalesces deltas, caches exact versions, uses stock ChatGPT and read-only worker',async()=>{const codex=new Fake(),events=[],w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000,publish:(device,event)=>events.push({device,event})});w.setEnabled('a',true);w.submit('a',[{id:'x',text:'Hel'}]);w.submit('a',[{id:'x',text:'Hello'},{id:'y',text:'Second'}]);await w.flush();assert.equal(codex.calls.filter(x=>x.method==='turn/start').length,1);assert.equal(events[0].event.translations[0].original,'Hello');const start=codex.calls.find(x=>x.method==='thread/start').args;assert.equal(start.sandbox,'read-only');assert.equal(start.ephemeral,true);assert.equal(start.approvalPolicy,'never');w.submit('a',[{id:'x',text:'Hello'}]);await w.flush();assert.equal(codex.calls.filter(x=>x.method==='turn/start').length,1);assert.equal(w.snapshot('a').translations.length,2);w.close();});
test('API-key login is refused and failed worker does not hot-loop',async()=>{const codex=new Fake();codex.call=async method=>{codex.calls.push({method});return {account:{type:'apiKey'}}};const w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.setEnabled('a',true);w.submit('a',[{id:'x',text:'Hello'}]);await w.flush();assert.equal(codex.calls.some(x=>x.method==='thread/start'),false);assert.equal(w.snapshot('a').translations.length,0);w.close();});
test('retains versioned historic public result while newer source stays queued',async()=>{const codex=new Fake(),w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.setEnabled('a',true);w.submit('a',[{id:'x',text:'Old'}]);w.translate=async batch=>{w.submit('a',[{id:'x',text:'New'}]);return {translations:batch.map(x=>({...x,text:'Vecchio',spans:[{source:x.text,occurrence:0,target:'Vecchio',unit:'phrase',note:''}]}))}};await w.flush();assert.equal(w.snapshot('a').translations[0].original,'Old');assert.equal(w.snapshot('a').translations[0].text,'Vecchio');assert.equal(w.state('a').queue.get('x').text,'New');w.close();});
test('translation ownership survives persistence without crossing devices or enabling others',async()=>{const records=new Map(),codex=new Fake(),events=[];let w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000,load:id=>records.get(id),save:(id,state)=>records.set(id,state),publish:(id,event)=>events.push({id,event})});w.setEnabled('a',true);w.setEnabled('b',true);w.submit('a',[{id:'same',text:'Private A'}]);w.submit('b',[{id:'same',text:'Private B'}]);await w.flush();assert.equal(w.snapshot('a').translations[0].original,'Private A');assert.equal(w.snapshot('b').translations[0].original,'Private B');assert.equal(events.filter(x=>x.id==='a')[0].event.translations[0].original,'Private A');w.close();w=new ImmersionWorker({codex,cwd:'/tmp',load:id=>records.get(id),save:(id,state)=>records.set(id,state)});assert.equal(w.snapshot('a').translations[0].original,'Private A');assert.equal(w.snapshot('new-device').enabled,false);w.close();});
test('never sends raw reasoning or tool payloads to the translation worker',async()=>{const codex=new Fake(),w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.setEnabled('a',true);w.submit('a',[{id:'raw',text:'Private hidden reasoning',kind:'reasoningRaw'},{id:'tool',text:'command parameters',kind:'toolPayload'}]);await w.flush();assert.equal(codex.calls.length,0);w.close();});
test('rejects a rendering that rewrites protected code or URLs',async()=>{const codex=new Fake(),w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.setEnabled('a',true);w.submit('a',[{id:'x',text:'Open `notes.md` and https://example.com/path'}]);w.translate=async batch=>({translations:batch.map(x=>({...x,text:'Apri `note.md` e https://example.com/other'}))});await w.flush();assert.equal(w.snapshot('a').translations.length,0);w.close();});
test('identical text under new surface IDs reuses persisted translations without another Codex turn',async()=>{const records=new Map(),codex=new Fake();let w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000,load:id=>records.get(id),save:(id,state)=>records.set(id,state)});w.setEnabled('a',true);w.submit('a',[{id:'chat',text:'Send the finished report.'}]);await w.flush();w.close();w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000,load:id=>records.get(id),save:(id,state)=>records.set(id,state)});const state=w.submit('a',[{id:'card',text:'Send the finished report.'},{id:'speech',text:'Send the finished report.'}]);await w.flush();assert.equal(codex.calls.filter(x=>x.method==='turn/start').length,1);assert.equal(state.translations.find(x=>x.id==='card').text,'Italiano Send the finished report.');assert.equal(state.translations.find(x=>x.id==='speech').original,'Send the finished report.');w.submit('b',[{id:'other',text:'Send the finished report.'}]);assert.equal(w.snapshot('b').translations.length,0);w.close();});
test('tilde and long-backtick command fences cannot be rewritten by a translation',async()=>{for(const fence of ['~~~','````']){const codex=new Fake(),w=new ImmersionWorker({codex,cwd:'/tmp',delay:100000});w.setEnabled('a',true);w.submit('a',[{id:'x',text:`Read this.\n\n${fence}sh\ngit status\n${fence}`}]);w.translate=async batch=>({translations:batch.map(x=>({...x,text:x.text.replace('git status','git diff')}))});await w.flush();assert.equal(w.snapshot('a').translations.length,0);w.close();}});

test('bounded batches prioritize urgent sources across devices and retain unselected updates',async()=>{const w=new ImmersionWorker({codex:new Fake(),cwd:'/tmp',delay:100000});w.setEnabled('ordinary',true);w.setEnabled('urgent',true);w.submit('ordinary',Array.from({length:20},(_,i)=>({id:String(i),text:'Public update '+String.fromCharCode(65+i)})));w.submit('urgent',[{id:'speech',text:'Speak now',kind:'speech urgent'}]);const batches=[];w.translate=async batch=>{batches.push(batch);return {translations:batch.map(x=>({...x,text:'Italiano '+x.text,spans:[{source:x.text,occurrence:0,target:'Italiano '+x.text,unit:'clause',note:''}]}))}};await w.flush();assert.equal(batches[0].length,2);assert.equal(batches[0][0].text,'Speak now');assert.equal(w.state('ordinary').queue.size,19);await w.flush();assert.equal(batches[1].length,6);assert.equal(w.state('ordinary').queue.size,13);w.close();});
