import test from 'node:test';import assert from 'node:assert/strict';
import {validateImmersionPlan,immersionHash,protectedImmersionRanges} from '../server/immersion-plan.mjs';
const row=(source,text,spans)=>({version:immersionHash(source),text,spans:spans.map(([source,target,occurrence=0])=>({source,target,occurrence,unit:'phrase',note:''}))});
test('complete contextual grammar units produce exact inline bilingual source',()=>{
 const source="I opened two new sessions and have an important question. I'm checking the model, then return to the session.";
 const text="I opened due nuove sessioni and have una domanda importante. Sto verificando il modello, then return alla sessione.";
 const result=validateImmersionPlan(source,row(source,text,[['two new sessions','due nuove sessioni'],['an important question','una domanda importante'],["I'm checking the model",'Sto verificando il modello'],['to the session','alla sessione']]));
 assert.equal(result.text,text);assert.equal(result.spans.length,4);for(const span of result.spans)assert.equal(source.slice(span.start,span.end),span.source);
});
test('UTF16 offsets resolved locally with repeated anchors and emoji',()=>{const source='🌍 the session and the session';const p=validateImmersionPlan(source,row(source,'🌍 the session and la sessione',[['the session','la sessione',1]]));assert.equal(p.spans[0].start,19);assert.equal(p.spans[0].end,30);});
test('wrong source version, overlap, substring splice and inconsistent hybrid are rejected',()=>{
 const source='two new sessions';const valid=row(source,'due nuove sessioni',[['two new sessions','due nuove sessioni']]);assert.equal(validateImmersionPlan(source,{...valid,version:'old'}),null);assert.equal(validateImmersionPlan(source,{...valid,text:'Invented claim'}),null);assert.equal(validateImmersionPlan(source,row(source,'bad',[['two new sessions','due nuove sessioni'],['new sessions','nuove sessioni']])),null);assert.equal(validateImmersionPlan(source,row(source,'two new sessionXYZ',[['s','XYZ',0]])),null);
});
test('executable syntax URLs filenames and model identifiers remain protected',()=>{const source='Open `notes.md`, run ```sh\ngit status\n``` with gpt-6-luna from /tmp/project and https://example.com --force';for(const token of ['notes.md','git status','gpt-6-luna','/tmp/project','https://example.com','--force'])assert.equal(validateImmersionPlan(source,row(source,source.replace(token,'changed'),[[token,'changed']])),null);assert.ok(protectedImmersionRanges(source).length>=5);});
test('complete fenced blocks including longer and tilde fences are protected',()=>{for(const f of ['~~~','````']){const source=`Before.\n${f}sh\necho hello\n${f}\nAfter.`;assert.equal(validateImmersionPlan(source,row(source,source.replace('echo hello','ciao'),[['echo hello','ciao']])),null)}});
test('numeric amounts percentages and deadlines cannot be included in replacement spans',()=>{for(const token of ['$12.50','68%','2026-10-04','10:30','3']){const source=`Preserve ${token} when checking the latest update.`;assert.equal(validateImmersionPlan(source,row(source,source.replace(token,'changed'),[[token,'changed']])),null);assert.ok(validateImmersionPlan(source,row(source,source.replace('the latest update','l’ultimo aggiornamento'),[['the latest update','l’ultimo aggiornamento']])));}});
test('spans cannot split surrogate pairs emoji sequences or combining characters',()=>{for(const [source,part]of [['🙂 here','\ude42'],['👩‍💻 here','👩'],['cafe\u0301 here','e']]){assert.equal(validateImmersionPlan(source,row(source,source.replace(part,'changed'),[[part,'changed']])),null)}const source='🙂 a new session';assert.ok(validateImmersionPlan(source,row(source,'🙂 una nuova sessione',[['a new session','una nuova sessione']])));});
