import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
function input(){const events=[],sources=[];let time=0;const source=readFileSync(new URL('../android/app/src/main/assets/native-voice.html',import.meta.url),'utf8').match(/<script>([\s\S]*)<\/script>/)[1].replace("connect().catch(e=>report('error',e.message));",'');const context=vm.createContext({PocketAudio:{event:(...e)=>events.push(e)},window:{},Date:{now:()=>0},setTimeout:()=>{},setInterval:()=>{},Float32Array,JSON,Blob,atob:s=>Buffer.from(s,'base64').toString('binary')});context.fakeCtx={get currentTime(){return time},createBuffer(_channels,n,rate){return {duration:n/rate,data:new Float32Array(n),getChannelData(){return this.data}}},createBufferSource(){const source={connect(){},start(at){this.at=at},stop(){this.stopped=true}};sources.push(source);return source}};vm.runInContext(source,context);context.remote={muted:false};vm.runInContext("ctx=fakeCtx;pc={connectionState:'connected'};dc={readyState:'open'};dest={};beginInput(3)",context);return {events,sources,network:rows=>{context.statsRows=rows;return vm.runInContext("pc.getStats=async()=>statsRows;networkBoundary('test')",context)},eval:code=>vm.runInContext(code,context),append(bytes,token=3){context.pcm=bytes.toString('base64');vm.runInContext(`appendInput(${token},pcm)`,context)},end(i){sources[i].onended?.()},time(value){time=value}}}
test('PCM is scheduled during capture and finish does not replay the full recording',()=>{const c=input();c.append(Buffer.alloc(3200));c.time(.1);c.append(Buffer.alloc(3200));assert.equal(c.sources.length,2);assert.ok(c.sources[1].at>=c.sources[0].at+.1);assert.equal(c.events.length,0);c.eval('finishInput(3)');c.end(0);assert.equal(c.events.length,0);c.end(1);assert.deepEqual(c.events,[['sent','']]);assert.equal(c.sources.length,2)});
test('little-endian signed PCM samples preserve source values',()=>{const c=input();const b=Buffer.alloc(6);b.writeInt16LE(-32768,0);b.writeInt16LE(0,2);b.writeInt16LE(32767,4);c.append(b);assert.equal(c.sources[0].buffer.data[0],-1);assert.equal(c.sources[0].buffer.data[2],32767/32768)});
test('cancelled capture stops its sources and cannot finish or append into its replacement',()=>{const c=input();c.append(Buffer.alloc(3200));c.eval('cancelInput();beginInput(5)');assert.equal(c.sources[0].stopped,true);c.end(0);c.append(Buffer.alloc(3200),3);assert.equal(c.sources.length,1);assert.throws(()=>c.eval('finishInput(3)'),/replaced/);c.append(Buffer.alloc(3200),5);c.eval('finishInput(5)');c.end(1);assert.deepEqual(c.events,[['sent','']])});
test('empty finished input settles once without launching coding or speaking',()=>{const c=input();c.eval('finishInput(3);finishInput(3)');assert.deepEqual(c.events,[['sent','']]);assert.equal(c.sources.length,0)});
test('malformed PCM fails visibly and excessive queued input is bounded',()=>{const c=input();assert.throws(()=>c.append(Buffer.alloc(1)),/Invalid PCM/);assert.throws(()=>c.append(Buffer.alloc(3840002)),/120 seconds/)});

test('network boundary telemetry contains timing and packet counts without candidate identities',async()=>{const c=input();await c.network(new Map([['secret-audio',{type:'inbound-rtp',kind:'audio',packetsReceived:8,packetsLost:1,jitter:.012,address:'DO_NOT_INCLUDE'}],['secret-pair',{type:'candidate-pair',state:'succeeded',nominated:true,currentRoundTripTime:.032,localCandidateId:'DO_NOT_INCLUDE',remoteCandidateId:'DO_NOT_INCLUDE'}]]));const sample=c.events.find(([kind])=>kind==='network');assert.ok(sample);const data=JSON.parse(sample[1]);assert.equal(data.samples[0].packetsReceived,8);assert.equal(data.samples[1].roundTripTime,.032);assert.ok(!sample[1].includes('DO_NOT_INCLUDE'));assert.ok(!sample[1].includes('secret-'))});
