import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
function capture(){let time=0,energy=0,stops=0;const events=[];const source=readFileSync(new URL('../android/app/src/main/assets/native-voice.html',import.meta.url),'utf8').match(/<script>([\s\S]*)<\/script>/)[1].replace('const explicitCompletion=false;','const explicitCompletion=true;').replace('connect().catch(e=>report(\'error\',e.message));','');const context=vm.createContext({PocketAudio:{event:(...x)=>events.push(x)},window:{},Date:{now:()=>time},setTimeout:()=>{},setInterval:()=>{},Float32Array,JSON,Blob});vm.runInContext(source,context);context.fakeAnalyser={getFloatTimeDomainData:a=>a.fill(energy)};context.fakeRecorder={state:'recording',start(){},stop(){stops++}};context.fakeRemote={muted:true,play:()=>Promise.resolve()};vm.runInContext('analyser=fakeAnalyser;recorder=fakeRecorder;remote=fakeRemote;speak(1,"The final words are silver lantern.")',context);return {event:e=>{context.e=e;vm.runInContext('providerEvent(e)',context)},sample:(at,value)=>{time=at;energy=value;vm.runInContext('sampleOutput()',context)},get stops(){return stops},events};}
const start=id=>({type:'turn.created',turn:{id,role:'assistant',start_ms:0,end_ms:200,transcript:'The'}});
const done=(id,extra={})=>({type:'turn.done',turn:{id,role:'assistant',start_ms:0,end_ms:4400,transcript:'The final words are silver lantern.',...extra}});
test('long internal silence cannot successfully finish saved speech before provider completion',()=>{const c=capture();c.event(start('one'));c.sample(100,.1);c.sample(4000,0);assert.equal(c.stops,0);c.sample(5000,.1);c.event(done('one'));c.sample(6000,0);assert.equal(c.stops,0);c.sample(7600,0);assert.equal(c.stops,1)});
test('stale turn completion and audio-done without final success do not cache truncated tail',()=>{const c=capture();c.event(start('current'));c.sample(100,.1);c.event({type:'response.output_audio.done'});c.event(done('previous'));c.sample(5000,0);assert.equal(c.stops,0)});
test('cancelled native turn fails visibly rather than completing interrupted audio',()=>{const c=capture();c.event(start('one'));c.sample(100,.1);c.event(done('one',{status:'cancelled'}));c.sample(6000,0);assert.equal(c.stops,0);assert.ok(c.events.some(([kind])=>kind==='error'))});
test('missing provider boundary never turns silence into success',()=>{const c=capture();c.sample(100,.1);c.sample(10000,0);assert.equal(c.stops,0)});
test('matching turn id with truncated final sentinel still cannot cache audio',()=>{const c=capture();c.event(start('one'));c.sample(100,.1);c.event(done('one',{transcript:'The final words are silver'}));c.sample(6000,0);assert.equal(c.stops,0);assert.ok(c.events.some(([kind])=>kind==='error'))});
test('completion timestamp cannot precede observed transcript tail',()=>{const c=capture();c.event(start('one'));c.event({type:'output_transcript.added',end_ms:7000});c.sample(100,.1);c.event(done('one'));c.sample(10000,0);assert.equal(c.stops,0)});
test('completed turn drains a minimum RTP tail rather than accepting preexisting silence immediately',()=>{const c=capture();c.event(start('one'));c.sample(100,.1);c.sample(5000,0);c.event(done('one'));c.sample(5100,0);assert.equal(c.stops,0);c.sample(5501,0);assert.equal(c.stops,1)});
