import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
function playback(live=true){let time=0,energy=0,stops=0;const events=[],timers=[];const source=readFileSync(new URL('../android/app/src/main/assets/native-voice.html',import.meta.url),'utf8').match(/<script>([\s\S]*)<\/script>/)[1].replace('const livePlayback=false;',`const livePlayback=${live};`).replace("connect().catch(e=>report('error',e.message));",'');const context=vm.createContext({PocketAudio:{event:(...e)=>events.push(e)},window:{},Date:{now:()=>time},setTimeout:f=>timers.push(f),setInterval:()=>{},Float32Array,JSON,Blob});vm.runInContext(source,context);context.remoteStub={muted:true,play:()=>Promise.resolve()};context.recorderStub={state:'inactive',start(){this.state='recording'},stop(){stops++;this.state='inactive'}};context.analyserStub={getFloatTimeDomainData:a=>a.fill(energy)};vm.runInContext('remote=remoteStub;recorder=recorderStub;analyser=analyserStub;speak(7)',context);return {context,events,timers,sample(at,value){time=at;energy=value;vm.runInContext('sampleOutput()',context)},eval(code){vm.runInContext(code,context)},get muted(){return context.remoteStub.muted},get stops(){return stops}}}
test('foreground live playback starts on first audio without waiting for the response tail',()=>{const p=playback();assert.equal(p.muted,false);p.sample(250,.1);assert.ok(p.events.some(([kind,token])=>kind==='speaking'&&token==='7'));assert.equal(p.stops,0);p.sample(600,.1);assert.equal(p.events.filter(([kind])=>kind==='speaking').length,1);assert.ok(p.events.some(([kind,data])=>kind==='timing'&&JSON.parse(data).elapsedMs===250))});
test('persisted notification renderer remains muted and buffered by default',()=>{const p=playback(false);p.sample(250,.1);assert.equal(p.muted,true);assert.ok(p.events.some(([kind])=>kind==='preparing'));assert.ok(!p.events.some(([kind])=>kind==='speaking'));p.sample(3000,0);assert.equal(p.stops,1)});
test('pause mutes only the current stream; resume and cancellation preserve isolation',()=>{const p=playback();p.sample(250,.1);p.eval('pauseOutput()');assert.equal(p.muted,true);p.eval('resumeOutput()');assert.equal(p.muted,false);p.eval('silence()');assert.equal(p.muted,true);p.eval('resumeOutput()');assert.equal(p.muted,true);p.sample(10000,.1);assert.equal(p.events.filter(([kind])=>kind==='speaking').length,2)});
test('live response completion retains cache capture and silences remote tail',()=>{const p=playback();p.sample(250,.1);p.sample(3000,0);assert.equal(p.stops,1);assert.equal(p.muted,true)});
test('no first audio produces an error rather than claiming successful speech',()=>{const p=playback();p.sample(22000,0);p.timers[0]();assert.ok(p.events.some(([kind])=>kind==='error'));assert.ok(!p.events.some(([kind])=>kind==='speaking'))});
test('cancelled generation timeout cannot fail a replacement response',()=>{const p=playback();p.eval('silence();speak(8)');p.sample(22000,0);p.timers[0]();assert.ok(!p.events.some(([kind])=>kind==='error'));p.timers[1]();assert.ok(p.events.some(([kind])=>kind==='error'))});
test('pausing before first audio never claims audible playback',()=>{const p=playback();p.eval('pauseOutput()');p.sample(250,.1);assert.equal(p.muted,true);assert.ok(!p.events.some(([kind])=>kind==='speaking'));p.sample(3000,0);assert.equal(p.stops,1)});
