import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {NotificationTitles} from '../server/notification-titles.mjs';
import {pushData,PushDelivery} from '../server/push.mjs';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE watches(thread_id TEXT PRIMARY KEY,name TEXT,enabled INTEGER);CREATE TABLE notifications(id INTEGER PRIMARY KEY,thread_id TEXT,title TEXT,body TEXT,kind TEXT,spoken_text TEXT);CREATE TABLE notification_attention(notification_id INTEGER PRIMARY KEY,resolved_at INTEGER);INSERT INTO watches VALUES('a','Old name',1),('b','Other task',1);INSERT INTO notifications VALUES(1,'a','Old name','Answer body','complete','Material polish. Answer body'),(2,'a','Question','Choose a finish','question','Material polish. Choose a finish'),(3,'b','Other task','Other answer','complete','Other context. Other answer');INSERT INTO notification_attention VALUES(2,NULL);`);return {db,titles:new NotificationTitles(db)};}
test('rename updates only that thread labels, watch source and queued push content while preserving bodies/context/attention',()=>{const {db,titles}=fixture();const before=db.prepare('SELECT * FROM notifications').all();const event=titles.rename('a','New name');assert.deepEqual(event.notificationIds,[1,2]);assert.equal(titles.title('a','Stale completion title'),'New name');const after=db.prepare('SELECT * FROM notifications').all();for(let i=0;i<after.length;i++){assert.equal(after[i].body,before[i].body);assert.equal(after[i].spoken_text,before[i].spoken_text);}assert.equal(after[2].title,'Other task');assert.equal(db.prepare('SELECT name FROM watches WHERE thread_id=?').get('a').name,'New name');assert.equal(db.prepare('SELECT resolved_at FROM notification_attention').get().resolved_at,null);assert.equal(pushData(after[0]).title,'New name');assert.equal(pushData(after[0]).spoken_text,'Material polish. Answer body');assert.equal(titles.rename('a','New name').changed,false);db.close();});
test('background rename sends only an authenticated-device label refresh, not a new ordinary notification',async()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE push_tokens(device_id TEXT PRIMARY KEY,token TEXT,project_id TEXT);INSERT INTO push_tokens VALUES('phone','token','project'),('other','other-token','other-project');`);const sent=[];const push=new PushDelivery(db,{config:{projectId:'project'},send:async x=>sent.push(x)});await push.renameThread({threadId:'task',name:'New name',notificationIds:[1,2]});assert.equal(sent.length,1);assert.equal(sent[0].data.device_id,'phone');assert.equal(sent[0].data.thread_renamed,'1');assert.equal(sent[0].data.thread_title,'New name');assert.equal(sent[0].data.id,undefined);assert.equal(sent[0].notification,undefined);db.close();});

test('historical Codex names reconcile once without using unnamed previews or changing notification content',()=>{const {db,titles}=fixture();const events=titles.reconcile([{id:'a',name:'Already renamed in Codex'},{id:'b',preview:'Not a custom title'},{id:'new',name:'Fresh named thread'}]);assert.equal(events.length,1);assert.equal(events[0].name,'Already renamed in Codex');assert.equal(events[0].revision,1);assert.deepEqual(titles.reconcile([{id:'a',name:'Already renamed in Codex'},{id:'new',name:'Fresh named thread'}]),[]);assert.equal(titles.title('b','fallback'),'Other task');assert.equal(db.prepare('SELECT body FROM notifications WHERE id=2').get().body,'Choose a finish');assert.equal(db.prepare('SELECT resolved_at FROM notification_attention').get().resolved_at,null);db.close();});
test('successive names have monotonically increasing revisions, duplicate reconciliation keeps revision',()=>{const {db,titles}=fixture();assert.equal(titles.rename('a','First').revision,1);assert.equal(titles.rename('a','Second').revision,2);assert.equal(titles.rename('a','Second').revision,2);const [event]=titles.reconcile([{id:'a',name:'Third'}]);assert.equal(event.revision,3);assert.equal(titles.revision('a'),3);assert.equal(pushData({id:1,title:'Third',title_revision:3}).title_revision,'3');db.close();});
