import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {DatabaseSync} from 'node:sqlite';
import {VoiceSpeech,speechPolicy,CHEAP_SPEECH_MODEL,NEXT_SPEECH_MODEL,SPEECH_UPGRADE_AT,normalizeSpeechWav} from '../server/voice-speech.mjs';
import {VoiceController,validateVoiceAudio} from '../server/voice-controller.mjs';
const wav=()=>{const b=Buffer.alloc(3244);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;};
const tick=()=>new Promise(r=>setImmediate(r));
class FakeCodex extends EventEmitter{constructor(){super();this.calls=[];}async connect(){} async call(method,params){this.calls.push({method,params});if(method==='thread/start')return {thread:{id:'controller-123'}};if(method==='turn/start')return {turn:{id:'turn-123'}};return {thread:{id:'controller-123'}};}answer(){}}
function setup(){const db=new DatabaseSync(':memory:'),codex=new FakeCodex(),calls=[];const controller=new VoiceController({db,codex,cwd:'/tmp',host:'test',transcribe:async()=> 'Queue a fix',api:async(path,body)=>{calls.push({path,body});if(path.startsWith('/api/threads?')||path==='/api/threads')return {threads:[{id:'controller-123'},{id:'task-123'}]};if(path==='/api/threads/task-123?view=timeline')return {thread:{id:'task-123',name:'Work',status:{type:'idle'}}};return {state:'queued'};}});return {db,codex,calls,controller};}
test('speech migration changes on every request at the exact retirement boundary',()=>{assert.equal(speechPolicy(Date.parse(SPEECH_UPGRADE_AT)-1).model,CHEAP_SPEECH_MODEL);assert.equal(speechPolicy(Date.parse(SPEECH_UPGRADE_AT)).model,NEXT_SPEECH_MODEL);});
test('cheap speech is used and authentication/quota/transient failures never silently upgrade',async()=>{let sent;const audio=wav();audio.writeUInt32LE(24000,24);const speech=new VoiceSpeech({apiKey:'secret',clock:()=>0,fetchImpl:async(_u,opts)=>{sent=JSON.parse(opts.body);return new Response(audio);}});assert.equal((await speech.synthesize('Hello')).model,CHEAP_SPEECH_MODEL);assert.equal(sent.voice,'marin');for(const status of [401,429,500]){speech.fetchImpl=async()=>new Response(JSON.stringify({error:{code:'model_not_found'}}),{status});speech.realtime=()=>{throw Error('Unexpected upgrade');};await assert.rejects(speech.synthesize('Hello'),new RegExp(String(status)));}assert.equal(JSON.stringify(speech.status()).includes('secret'),false);});
test('explicit unavailable old model migrates, malformed audio fails, empty requests do not spend',async()=>{const speech=new VoiceSpeech({apiKey:'secret',clock:()=>0,fetchImpl:async()=>new Response(JSON.stringify({error:{code:'model_deprecated'}}),{status:404})});speech.realtime=async()=>({model:NEXT_SPEECH_MODEL});assert.equal((await speech.synthesize('Hello')).model,NEXT_SPEECH_MODEL);speech.fetchImpl=async()=>new Response('not audio');await assert.rejects(speech.synthesize('Hello'),/invalid audio/);await assert.rejects(speech.synthesize(''),/characters/);});
test('Realtime renderer uses manual out-of-conversation audio and handles duplicate session updates once',async()=>{let socket;class FakeSocket extends EventEmitter{constructor(){super();socket=this;this.sent=[];queueMicrotask(()=>this.emit('open'));}send(raw){const m=JSON.parse(raw);this.sent.push(m);if(m.type==='session.update')queueMicrotask(()=>{this.emit('message',Buffer.from(JSON.stringify({type:'session.updated'})));this.emit('message',Buffer.from(JSON.stringify({type:'session.updated'})));});if(m.type==='response.create')queueMicrotask(()=>{this.emit('message',Buffer.from(JSON.stringify({type:'response.output_audio.delta',delta:Buffer.from([0,0,1,0]).toString('base64')})));this.emit('message',Buffer.from(JSON.stringify({type:'response.done',response:{status:'completed'}})));});}terminate(){}}
const speech=new VoiceSpeech({apiKey:'secret',clock:()=>Date.parse(SPEECH_UPGRADE_AT),WebSocketImpl:FakeSocket});const r=await speech.synthesize('Read this literally.');assert.equal(r.audio.toString('ascii',0,4),'RIFF');assert.equal(r.audio.readUInt32LE(24),24000);assert.equal(r.audio.readUInt32LE(40),4);assert.equal(socket.sent.filter(x=>x.type==='response.create').length,1);assert.equal(socket.sent[1].response.conversation,'none');assert.equal(socket.sent[0].session.audio.input.turn_detection,null);});
test('the phone audio contract rejects incompatible, partial or oversized recordings',()=>{validateVoiceAudio(wav());const b=wav();b.writeUInt32LE(48000,24);assert.throws(()=>validateVoiceAudio(b));assert.throws(()=>validateVoiceAudio(Buffer.from('invalid')));});
test('voice is a durable per-device Codex session, commands and tool calls never replay after retries',async()=>{const {controller,codex,db,calls}=setup();await controller.ensure('phone');await controller.ensure('phone');assert.equal(codex.calls.filter(c=>c.method==='thread/start').length,1);assert.equal(codex.calls[0].params.dynamicTools[0].name,'pocket_control');controller.submit('phone','command-123',wav());await tick();await tick();const a=controller.active.get('controller-123');assert.ok(a);controller.submit('phone','command-123',wav());assert.equal(codex.calls.filter(c=>c.method==='turn/start').length,1);assert.equal(controller.get('another-device','command-123'),null);await controller.control(a,{operation:'select',arguments:{threadId:'task-123'}});const p={tool:'pocket_control',callId:'call-123',arguments:{operation:'reply',arguments:{text:'Fix this',mode:'queue'}}};const r=await controller.tool(a,p);assert.equal(r.success,true);assert.deepEqual(await controller.tool(a,p),r);assert.equal(calls.filter(x=>x.path.endsWith('/reply')).length,1);assert.equal(calls.at(-1).body.mode,'queue');codex.emit('event',{method:'item/completed',params:{threadId:'controller-123',item:{type:'agentMessage',phase:'commentary',text:'Checking'}}});codex.emit('event',{method:'item/completed',params:{threadId:'controller-123',item:{type:'agentMessage',phase:'final_answer',text:'Fix queued now. It will run next.'}}});codex.emit('event',{method:'turn/completed',params:{threadId:'controller-123',turn:{id:'turn-123',status:'completed'}}});assert.equal(controller.get('phone','command-123').response,'Fix queued now. It will run next.');const changed=wav();changed[100]=1;assert.throws(()=>controller.submit('phone','command-123',changed),/different recording/);db.close();});
test('lost controller connection marks work uncertain and a server restart cannot execute it again',async()=>{const {controller,codex,db}=setup();await controller.ensure('phone');controller.submit('phone','command-123',wav());await tick();await tick();codex.emit('disconnected');assert.equal(controller.get('phone','command-123').state,'unknown');controller.submit('phone','command-123',wav());assert.equal(codex.calls.filter(x=>x.method==='turn/start').length,1);db.prepare("UPDATE voice_turns SET state='thinking'").run();new VoiceController({db,codex:new FakeCodex()});assert.equal(controller.get('phone','command-123').state,'unknown');db.close();});
test('controller cannot send work into itself or silently answer with guessed permissions',async()=>{const {controller,db}=setup();await controller.ensure('phone');const a={device:'phone',id:'command-123'};await assert.rejects(controller.control(a,{operation:'reply',arguments:{threadId:'controller-123',text:'Oops'}}),/Select a work session/);await assert.rejects(controller.control(a,{operation:'permissions',arguments:{full:'yes'}}),/Choose full/);await assert.rejects(controller.control(a,{operation:'profile',arguments:{local:'phone'}}),/Choose phone/);db.close();});

test('streamed Mini TTS WAV headers are repaired into Android-playable finite files',()=>{const audio=wav();audio.writeUInt32LE(24000,24);audio.writeUInt32LE(0xffffffff,4);audio.writeUInt32LE(0xffffffff,40);const fixed=normalizeSpeechWav(audio);assert.equal(fixed.readUInt32LE(4),fixed.length-8);assert.equal(fixed.readUInt32LE(40),fixed.length-44);assert.deepEqual(fixed.subarray(44),audio.subarray(44));});

test('coordinator history persists, paginates equal-time turns and is device scoped',()=>{
 const {controller,db}=setup();const put=db.prepare("INSERT INTO voice_turns(device,id,hash,state,transcript,response,created_at) VALUES(?,?,?,'completed',?,?,?)");
 for(let i=0;i<105;i++)put.run('phone','history-'+i,'hash','Input '+i,'Reply '+i,1234);
 put.run('other','private-turn','hash','Private input','Private reply',1234);
 const page=controller.history('phone');assert.equal(page.turns.length,100);assert.equal(page.hasEarlier,true);assert.equal(page.turns[0].transcript,'Input 5');assert.equal(page.turns.at(-1).response,'Reply 104');
 const earlier=controller.history('phone',page.before);assert.equal(earlier.turns.length,5);assert.equal(earlier.hasEarlier,false);assert.equal(earlier.turns[0].transcript,'Input 0');assert.equal(controller.history('unpaired').turns.length,0);db.close();
});
