import {spawnSync} from 'node:child_process';
import {copyFileSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {join,resolve,isAbsolute} from 'node:path';
import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('..',import.meta.url));
for(const key of ['POCKET_SIGNING_STORE','POCKET_SIGNING_PASSWORD'])if(!process.env[key])throw Error(`${key} is required; see docs/RELEASING.md. No debug-key fallback.`);
if(!isAbsolute(process.env.POCKET_SIGNING_STORE))throw Error('Use an absolute signing-store path outside the checkout.');
const store=resolve(process.env.POCKET_SIGNING_STORE);
if(store.startsWith(root))throw Error('Keep the signing key outside the checkout.');
const version=JSON.parse(readFileSync(join(root,'package.json'))).version;
const result=spawnSync('./gradlew',['--no-daemon','testDebugUnitTest','assembleRelease','lintRelease'],{cwd:join(root,'android'),stdio:'inherit'});
if(result.status!==0)process.exit(result.status||1);
const sdk=process.env.ANDROID_HOME||process.env.ANDROID_SDK_ROOT;
if(!sdk)throw Error('Set ANDROID_HOME so the release can be checked with apksigner.');
const source=join(root,'android/app/build/outputs/apk/release/app-release.apk');
const verify=spawnSync(join(sdk,'build-tools/36.0.0/apksigner'),['verify','--verbose','--print-certs',source],{encoding:'utf8'});
if(verify.status!==0)throw Error('APK signature verification failed: '+verify.stderr);
const out=join(root,'dist');mkdirSync(out,{recursive:true});
const name=`pocodex-${version}.apk`;copyFileSync(source,join(out,name));
writeFileSync(join(out,'SHA256SUMS.txt'),createHash('sha256').update(readFileSync(source)).digest('hex')+'  '+name+'\n');
writeFileSync(join(out,'SIGNING-CERTIFICATE.txt'),verify.stdout);
console.log(`Signed release prepared in dist/${name}. Verify the certificate against the maintained release identity before publishing.`);
