import {sessionIdentity,workTime,compareWork,mergeRows,pendingFor} from './model.mjs';
import {read,write,clear} from './storage.mjs';
import {BrowserVoice} from './voice.mjs';
const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let scope=read('scope','coordinator'),deviceId='',threads=[],current=null,status=null,ws=null,authenticated=false,polling=false,installEvent=null,models=[],loadSerial=0,earlierBusy=false,reconnectTimer,follow=true;
let seatOrder=[],deliveryFlight=null,startFlight=null;
const cache=new Map(),receipts=new Set(),notifySeen=new Set();let pending=read('pending',null),newPending=read('newPending',null);
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await r.json();}catch{data={error:`Backend returned HTTP ${r.status}.`};}if(!r.ok){if(r.status===401&&authenticated){authenticated=false;ws?.close();$('app').hidden=true;$('pairing').hidden=false;}throw Object.assign(Error(data.error||`Request failed (${r.status}).`),{status:r.status});}return data;}
const error=e=>{$('error').textContent=e.message||String(e);$('error').hidden=false;};
const run=fn=>async(...args)=>{try{$('error').hidden=true;await fn(...args);}catch(e){error(e);}};
const voice=new BrowserVoice(api,(text,p)=>{$('voice-status').hidden=!text;$('voice-status').replaceChildren(document.createTextNode(text));if(text.includes('speech')){const stop=el('button','','Stop speech');stop.onclick=run(()=>voice.disconnect());$('voice-status').append(stop);} $('mic').classList.toggle('recording',!!voice.recording);$('mic').textContent=voice.recording?'■ Stop recording':'● Mic';$('voice-send').hidden=!p;$('voice-clear').hidden=!p;$('voice-send').disabled=!!p&&p.scope!==scope;});
function draftKey(s=scope){return `draft.${deviceId}.${s}`;}
function saveDraft(){if(deviceId)write(draftKey(),$('draft').value);}
function persistPending(value){pending=value;write('pending',value);renderOutbox();}
function button(label,action){const b=el('button','',label);b.type='button';b.onclick=run(action);return b;}
function stamp(ms){if(!ms)return 'Recency unknown';const d=Math.max(0,Date.now()-ms);return d<60000?'Just now':d<3600000?`${Math.floor(d/60000)}m ago`:d<86400000?`${Math.floor(d/3600000)}h ago`:new Date(ms).toLocaleDateString();}
function renderList(){const search=$('search').value.toLowerCase(),filter=$('filter').value;const visible=threads.filter(t=>(filter!=='active'||['active','pending'].includes(t.status?.type))&&[t.name,t.preview,t.cwd,t.agentNickname].some(x=>String(x||'').toLowerCase().includes(search)));if(!seatOrder.length)seatOrder=[...threads].sort(compareWork).map(t=>t.id);for(const t of [...threads].sort(compareWork))if(!seatOrder.includes(t.id)){const position=seatOrder.findIndex(id=>compareWork(t,threads.find(x=>x.id===id)||{id})<0);seatOrder.splice(position<0?seatOrder.length:position,0,t.id);}const sorted=[...visible].sort((a,b)=>seatOrder.indexOf(a.id)-seatOrder.indexOf(b.id)),byId=new Map(sorted.map(t=>[t.id,t])),placed=new Set(),ordered=[];
 const add=t=>{if(placed.has(t.id))return;placed.add(t.id);ordered.push(t);for(const c of sorted)if(sessionIdentity(c).parentThreadId===t.id)add(c);};for(const t of sorted)if(!byId.has(sessionIdentity(t).parentThreadId))add(t);for(const t of sorted)add(t);
 const old=new Map([...$('work-list').children].map(n=>[n.dataset.id,n]));let cursor=$('work-list').firstChild;
 for(const t of ordered){let n=old.get(t.id);if(!n){n=button('',()=>open(t.id));n.dataset.id=t.id;n.append(el('span','card-title'),el('span','preview'),el('span','card-meta'));}old.delete(t.id);const identity=sessionIdentity(t);n.className='work-card'+(scope===t.id?' selected':'')+(identity.isChild?' child':'');n.setAttribute('aria-current',scope===t.id?'page':'false');n.title=t.name;n.children[0].textContent=t.name||t.agentNickname||'Untitled work';n.children[1].textContent=t.preview||'Open to see the conversation';n.children[2].replaceChildren(el('span','',`${identity.isChild?'Agent · ':''}${t.status?.type||'Unknown'}${t.unreadCount?' · '+t.unreadCount+' unread':''}`),el('span','',stamp(workTime(t))));n.style.setProperty('--recency',`hsl(155 22% ${Math.min(77,35+Math.log2(1+Math.max(0,Date.now()-workTime(t))/60000)*4)}%)`);if(n!==cursor)$('work-list').insertBefore(n,cursor);cursor=n.nextSibling;}
 for(const n of old.values())n.remove();if(!ordered.length)$('catalog-note').textContent='No work matches this view.';
}
function renderHeader(){const t=scope==='coordinator'?null:current?.thread||threads.find(t=>t.id===scope),identity=sessionIdentity(t);$('title').textContent=t?.name||t?.agentNickname||'Coordinator';$('context-label').textContent=t?identity.isChild?'DELEGATED WORK':'DIRECT SESSION':'DIRECT YOUR COMPUTING';$('session-state').textContent=t?`${t.status?.type||'Status unavailable'} · ${t.cwd||'Work environment'}${identity.isChild&&!identity.canAcceptDirectInput?' · Guide through the parent task':''}`:'Ask here, or open work to guide it directly.';$('coordinator').classList.toggle('active',scope==='coordinator');$('session-menu').hidden=!t||(identity.isChild&&!identity.canAcceptDirectInput);$('parent').hidden=!identity.parentThreadId;$('parent').onclick=run(()=>open(identity.parentThreadId));const enabled=scope==='coordinator'||!!current&&identity.canAcceptDirectInput;$('draft').disabled=!enabled;$('send').disabled=!enabled||!!deliveryFlight||!!pending;$('mic').disabled=!enabled||!voice.supported();$('draft').placeholder=!enabled?'Open the parent task to send guidance…':t?'Guide this session…':'Tell the coordinator what you need…';$('send-mode').hidden=!t;}
function richText(text){const fragment=document.createDocumentFragment();const pieces=String(text||'').split(/(```[\s\S]*?```)/g);for(const part of pieces){if(part.startsWith('```')){fragment.append(el('pre','',part.replace(/^```[^\n]*\n?/,'').replace(/```$/,'')));continue;}const lines=part.split(/(\[[^\]\n]+\]\(https?:\/\/[^\s)]+\)|`[^`\n]+`)/g);for(const bit of lines){if(bit.startsWith('`'))fragment.append(el('code','',bit.slice(1,-1)));else{const m=/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/.exec(bit);if(m){const a=el('a','',m[1]);a.href=m[2];a.target='_blank';a.rel='noopener noreferrer';fragment.append(a);}else fragment.append(document.createTextNode(bit));}}}return fragment;}
function rowNode(row){let n;if(['turn','turnEnd'].includes(row.kind))return el('div','turn-label',row.kind==='turn'?`${row.status||'Turn'}${row.startedAt?' · '+new Date(row.startedAt*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}`:`${row.status||'Finished'}${row.text?' · '+row.text:''}`);
 if(row.kind==='request')return el('div','turn-label','Decision needed — answer below');
 if(row.kind==='attachments'){n=el('div','message');n.append(el('header','',row.title));for(const a of row.attachments||[]){const b=button(a.name||'Open attachment',async()=>{if(!/^\/api\/files\/[a-zA-Z0-9_-]+$/.test(a.url))throw Error('Unsupported attachment URL.');window.open(a.url,'_blank','noopener');});n.append(b);}return n;}
 if(row.kind==='activity'){n=el('details','activity');n.append(el('summary','',`${row.title||row.type} · ${row.text||row.status||''}`));if(row.detail)n.append(el('pre','',row.detail));return n;}
 n=el('article','message'+(row.kind==='user'?' user':''));n.append(el('header','',row.title||'NextComp'));const body=el('div','body');body.append(richText(row.text));n.append(body);if(row.kind!=='user'){const actions=el('div','message-actions');actions.append(button('Reply to this',()=>{$('draft').value=`About this update: “${String(row.text||'').slice(0,220)}”\n\n${$('draft').value}`;saveDraft();$('draft').focus();}),button('Speak',()=>voice.speak(row.text)));n.append(actions);}return n;
}
function renderTranscript(){const data=cache.get(scope);if(!data)return;const list=$('transcript'),bottom=list.scrollHeight-list.scrollTop-list.clientHeight<90,previousHeight=list.scrollHeight,previousTop=list.scrollTop,important=$('important').checked;
 const rows=scope==='coordinator'?(data.turns||[]).flatMap(t=>[{id:t.id+'/user',kind:'user',title:'You',text:t.transcript||'',turnId:t.id},{id:t.id+'/response',kind:'message',title:`Coordinator · ${t.state}`,text:t.response||t.error||'Working…',turnId:t.id,actions:t.actions}]):data.rows||[];
 const old=new Map([...list.children].map(n=>[n.dataset.id,n]));let cursor=list.firstChild;for(const row of rows){if(important&&!['message','user','request','attachments'].includes(row.kind))continue;const signature=JSON.stringify(row);let n=old.get(row.id);if(n?.dataset.signature!==signature){const previous=n;n=rowNode(row);n.dataset.id=row.id;n.dataset.signature=signature;if(row.actions?.length){const actions=el('div','message-actions');for(const a of row.actions.filter(a=>a.threadId))actions.append(button(`Open ${a.name||'work'}`,()=>open(a.threadId)));n.append(actions);}if(previous){if(previous.open)n.open=true;previous.replaceWith(n);if(cursor===previous)cursor=n;}}old.delete(row.id);if(n!==cursor)list.insertBefore(n,cursor);cursor=n.nextSibling;}
 for(const n of old.values())n.remove();$('earlier').hidden=!data.hasEarlier;if(follow&&bottom)list.scrollTop=list.scrollHeight;else list.scrollTop=previousTop;requestAnimationFrame(ackVisible);
}
function renderRequests(){const holder=$('requests');if(scope==='coordinator'){holder.replaceChildren();return;}const requests=current?.pending||[],signature=JSON.stringify(requests);if(holder.dataset.signature===signature)return;holder.dataset.signature=signature;holder.replaceChildren();for(const r of requests){const box=el('div','request-card');box.append(el('p','',r.params?.message||r.params?.command||'This session needs your decision.'));if(/requestUserInput$/.test(r.method)){const answers={};for(const q of r.params?.questions||[]){const label=el('label','',q.question),input=el('input');input.placeholder='Your answer';input.setAttribute('aria-label',q.question);label.append(input);box.append(label);for(const o of q.options||[])box.append(button(o.label,()=>{input.value=o.label;}));answers[q.id]=input;}box.append(button('Submit answers',async()=>{await api(`/api/requests/${encodeURIComponent(r.id)}/answer`,{answers:Object.fromEntries(Object.entries(answers).map(([id,n])=>[id,n.value]))});await refreshConversation();}),button('Skip',async()=>{await api(`/api/requests/${encodeURIComponent(r.id)}/answer`,{skip:true});await refreshConversation();}));}
 else if(/item\/(commandExecution|fileChange)\/requestApproval$/.test(r.method)){for(const decision of r.params?.availableDecisions||['accept','decline','cancel'])if(['accept','decline','cancel'].includes(decision))box.append(button({accept:'Allow once',decline:'Decline',cancel:'Cancel'}[decision],async()=>{await api(`/api/requests/${encodeURIComponent(r.id)}/answer`,{decision});await refreshConversation();}));}else box.append(el('p','muted','This request type must be answered in the terminal.'));holder.append(box);}}
function renderOutbox(){const holder=$('outbox');holder.replaceChildren();if(newPending){const row=el('div','outbox-row',`Task creation ${newPending.state||'pending'} · ${newPending.prompt.slice(0,80)}`);row.append(button('Check creation',reconcileStart));if(newPending.state==='unknown')row.append(button('Clear after reviewing work',()=>{if(confirm('Check recent work first. Clearing this receipt does not undo a created task; starting again could duplicate work. Clear it?')){newPending=null;write('newPending',null);renderOutbox();}}));holder.append(row);}if(pending){const row=el('div','outbox-row',`${pending.scope===scope?'':'Another conversation · '}Saved send · ${pending.text.slice(0,90)} — checking delivery`);row.append(button('Check delivery',reconcilePending));holder.append(row);}for(const o of current?.outgoing||[]){if(['accepted','cancelled'].includes(o.state))continue;const row=el('div','outbox-row',`${o.state} · ${o.text?.slice(0,100)||'Message'}`);if(['failed','unknown','held','queued'].includes(o.state)){row.append(button('Remove',async()=>{await api(`/api/threads/${scope}/replies/${o.id}`,{action:'remove'});await refreshConversation();}));if(['queued','held','failed'].includes(o.state))row.append(button('Edit',async()=>{const text=prompt('Edit failed message',o.text);if(text){await api(`/api/threads/${scope}/replies/${o.id}`,{action:'edit',text});await refreshConversation();}}));if(['queued','held'].includes(o.state))row.append(button('Send now',async()=>{await api(`/api/threads/${scope}/replies/${o.id}`,{action:'send'});await refreshConversation();}));if(['failed','unknown'].includes(o.state))row.append(button('Retry',async()=>{if(o.state==='unknown'&&!confirm('Delivery is uncertain. Retrying can duplicate work. Check the conversation first. Retry anyway?'))return;await api(`/api/threads/${scope}/replies/${o.id}`,{action:'retry',confirmUnknown:o.state==='unknown'});await refreshConversation();}));}holder.append(row);}}
async function ackVisible(){if(document.visibilityState!=='visible'||!authenticated||document.querySelector('dialog[open]')||$('main').getBoundingClientRect().width===0)return;const data=cache.get(scope),root=$('transcript').getBoundingClientRect();if(!data)return;const rendered=[...$('transcript').children];const visible=n=>{const r=n.getBoundingClientRect();return r.top>=root.top&&r.bottom<=root.bottom;};if(scope==='coordinator'){for(const t of data.turns||[]){const n=rendered.find(n=>n.dataset.id===t.id+'/response'),key=deviceId+':'+t.id;if(t.state==='completed'&&n&&visible(n)&&!receipts.has(key)){receipts.add(key);api(`/api/voice/turns/${t.id}/presented`,{}).catch(()=>receipts.delete(key));}}}else if(data.catchup?.token&&!$('important').checked&&rendered.length&&rendered.every(visible)){const key=data.catchup.token;if(!receipts.has(key)){receipts.add(key);api(`/api/threads/${scope}/catchup/read`,{token:key}).catch(()=>receipts.delete(key));}}}
async function open(id){saveDraft();scope=id;write('scope',scope);follow=true;current=id==='coordinator'?null:cache.get(id)?.snapshot||null;$('draft').value=read(draftKey(),'');$('requests').dataset.signature='';$('error').hidden=true;$('transcript').replaceChildren();$('attention-panel').hidden=true;$('reports-panel').hidden=true;document.body.classList.add('chat-open');renderHeader();renderList();renderTranscript();renderRequests();renderOutbox();$('voice-send').disabled=!!voice.pending&&voice.pending.scope!==scope;await refreshConversation();$('transcript').scrollTop=$('transcript').scrollHeight;}
async function refreshConversation(before=null){const selected=scope,serial=++loadSerial;const old=cache.get(selected)||{};if(selected==='coordinator'){const data=await api('/api/voice/history?conversationOnly=1'+(before?'&before='+before:''));if(scope!==selected||(!before&&serial!==loadSerial))return;const turns=before?[...data.turns,...(old.turns||[])]:[...(old.turns||[]).filter(t=>!data.turns.some(x=>x.id===t.id)),...data.turns];cache.set(selected,{...data,turns,...(!before&&old.hasEarlier?{hasEarlier:true,before:old.before}:{})});current=null;}else{const data=await api(`/api/threads/${encodeURIComponent(selected)}?view=timeline`+(before?'&before='+encodeURIComponent(before):''));if(scope!==selected||(!before&&serial!==loadSerial))return;const rows=before?mergeRows(data.timeline.rows,old.rows||[]):mergeRows(old.rows||[],data.timeline.rows);current=before?old.snapshot||data:data;cache.set(selected,{...data.timeline,rows,snapshot:current,catchup:data.catchup,...(!before&&old.hasEarlier?{hasEarlier:true,before:old.before}:{})});}
 renderHeader();renderTranscript();renderRequests();renderOutbox();}
async function loadEarlier(){const data=cache.get(scope);if(!data?.hasEarlier||earlierBusy)return;earlierBusy=true;const height=$('transcript').scrollHeight,top=$('transcript').scrollTop;try{await refreshConversation(data.before);$('transcript').scrollTop=top+$('transcript').scrollHeight-height;}finally{earlierBusy=false;}}
async function refreshList(){const data=await api('/api/threads'+($('filter').value==='archived'?'?archived=true':''));threads=data.threads||[];$('catalog-note').textContent=data.catalogPartial?'Showing a bounded inventory. Search or open known work.':'';renderList();}
async function send(){const text=$('draft').value.trim();if(!text)return;if(deliveryFlight)await deliveryFlight;if(pending)throw Error('Check the saved message delivery before sending another.');saveDraft();const message={...pendingFor(scope,text,$('send-mode').value),deviceId};persistPending(message);await deliverPending();}
function clearDelivered(message){if(message.scope===scope&&$('draft').value.trim()===message.text){$('draft').value='';saveDraft();}else if(read(draftKey(message.scope),'').trim()===message.text)write(draftKey(message.scope),'');persistPending(null);}
async function deliverPending(){if(deliveryFlight)return deliveryFlight;deliveryFlight=performPending();try{return await deliveryFlight;}finally{deliveryFlight=null;renderHeader();}}
async function performPending(){const p=pending;if(!p||p.deviceId!==deviceId)throw Error('Saved delivery belongs to another paired device.');$('send').disabled=true;try{if(p.scope==='coordinator'){await api('/api/voice/start',{threadId:null});await api('/api/voice/text',{turnId:p.id,text:p.text});}else await api(`/api/threads/${p.scope}/reply`,{id:p.id,text:p.text,mode:p.mode});clearDelivered(p);await refreshConversation();await refreshList();}catch(e){if(e.status&&e.status<500){persistPending(null);}throw e;}finally{renderHeader();}}
async function reconcilePending(){if(deliveryFlight)return deliveryFlight;if(!pending)return;const p=pending;if(p.deviceId!==deviceId)throw Error('This saved send belongs to another browser pairing.');const path=p.scope==='coordinator'?`/api/voice/turns/${p.id}`:`/api/replies/${p.id}`;try{await api(path);clearDelivered(p);await refreshConversation();}catch(e){if(e.status!==404)throw e;if(pending?.id===p.id)await deliverPending();}}
function connectEvents(){clearTimeout(reconnectTimer);if(!authenticated)return;ws?.close();ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/events`);const own=ws;ws.onopen=()=>{$('connection').textContent='Connected';void run(async()=>{await refreshList();await refreshConversation();await reconcilePending();})()};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='timeline'&&m.threadId===scope){const data=cache.get(scope);if(data&&m.row){data.rows=mergeRows(data.rows||[],[m.row]);renderTranscript();}scheduleRefresh();}else if(m.type==='threadPreview'){const t=threads.find(t=>t.id===m.threadId);if(t){Object.assign(t,m);renderList();}}else if(m.type==='notification'){if(document.visibilityState==='hidden'&&'Notification' in window&&Notification.permission==='granted'&&!notifySeen.has(m.notification.id)){notifySeen.add(m.notification.id);const n=new Notification('NextComp update',{body:'Work has an update. Open NextComp to review it.',tag:'nextcomp-'+m.notification.thread_id});n.onclick=()=>{window.focus();if(m.notification.thread_id)void run(()=>open(m.notification.thread_id))();n.close();};}scheduleRefresh();}else scheduleRefresh();};ws.onclose=()=>{if(ws!==own||!authenticated)return;$('connection').textContent='Reconnecting…';reconnectTimer=setTimeout(connectEvents,3000);};ws.onerror=()=>own.close();}
let refreshTimer;function scheduleRefresh(){if(refreshTimer)return;refreshTimer=setTimeout(()=>{refreshTimer=null;if(authenticated&&document.visibilityState==='visible')void run(async()=>{await refreshConversation();await refreshAttention();})()},800);}
async function refreshAttention(){const data=await api('/api/attention');$('attention-count').textContent=data.notifications.length;$('attention-panel').replaceChildren(el('h2','','Needs your attention'));for(const n of data.notifications){const box=el('div','inbox-item');box.append(el('p','',n.title),el('p','',n.body),button('Open original work',()=>open(n.thread_id)));$('attention-panel').append(box);}}
async function showReports(before=null){const data=await api('/api/coordinator/reports'+(before?'?before='+before:''));if(!before)$('reports-panel').replaceChildren(el('h2','','Work updates'));for(const r of data.reports||data.items||[]){const box=el('div','inbox-item');box.append(el('p','',r.response||r.text||''),button('Mark this report read',async()=>{await api(`/api/voice/turns/${r.id}/presented`,{});}));for(const a of r.actions||[])if(a.threadId)box.append(button('Open work',()=>open(a.threadId)));$('reports-panel').append(box);}if($('reports-panel').children.length===1)$('reports-panel').append(el('p','muted','No scheduled reports yet. Enable scheduling in Settings for this browser.'));if(data.hasEarlier)$('reports-panel').append(button('Older reports',()=>showReports(data.before)));if(!before)$('reports-panel').hidden=!$('reports-panel').hidden;document.body.classList.add('chat-open');}
async function boot(){try{status=await api('/api/status');deviceId=status.deviceId;authenticated=true;$('pairing').hidden=true;$('app').hidden=false;$('host-info').textContent=`${status.host} · ${status.version} · ${status.device}`;if(read('deviceId')&&read('deviceId')!==deviceId){clear();pending=null;newPending=null;scope='coordinator';}write('deviceId',deviceId);$('cwd').value=status.defaultCwd||'';await refreshList();await open(scope);await refreshAttention();connectEvents();await voice.restore();if(pending)await reconcilePending();if(newPending)await reconcileStart();}catch(e){if(e.status===401){$('pairing').hidden=false;$('app').hidden=true;}else error(e);}}
$('pair-form').onsubmit=async e=>{e.preventDefault();const b=$('pair-form').querySelector('button');b.disabled=true;try{await api('/web/pair',Object.fromEntries(new FormData(e.target)));await boot();}catch(err){$('pair-error').textContent=err.message;}finally{b.disabled=false;}};
$('composer').onsubmit=run(async e=>{e.preventDefault();await send();});$('draft').oninput=saveDraft;$('draft').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();void run(send)();}};
$('coordinator').onclick=run(()=>open('coordinator'));$('refresh').onclick=run(async()=>{seatOrder=[];await refreshList();});$('search').oninput=renderList;$('filter').onchange=run(async()=>{seatOrder=[];await refreshList();});$('back').onclick=()=>{saveDraft();document.body.classList.remove('chat-open');seatOrder=[];renderList();};$('important').onchange=renderTranscript;$('earlier').onclick=run(loadEarlier);$('latest').onclick=()=>{follow=true;$('transcript').scrollTop=$('transcript').scrollHeight;};$('transcript').onscroll=()=>{follow=$('transcript').scrollHeight-$('transcript').scrollTop-$('transcript').clientHeight<90;void ackVisible();if($('transcript').scrollTop<100)void run(loadEarlier)();};
$('attention-toggle').onclick=run(async()=>{await refreshAttention();$('attention-panel').hidden=!$('attention-panel').hidden;document.body.classList.add('chat-open');});$('reports-toggle').onclick=run(()=>showReports());$('settings').onclick=run(async()=>{$('settings-dialog').showModal();const prefs=await api('/api/coordinator/reporting');$('report-enabled').checked=prefs.enabled;$('report-interval').value=prefs.intervalMinutes;$('report-stale').value=prefs.staleAfterMinutes;});$('save-reporting').onclick=run(async()=>{await api('/api/coordinator/reporting',{enabled:$('report-enabled').checked,intervalMinutes:Number($('report-interval').value),staleAfterMinutes:Number($('report-stale').value)});$('settings-dialog').close();});$('notifications').onclick=run(async()=>{if(!('Notification' in window))throw Error('Browser notifications are unavailable.');const permission=await Notification.requestPermission();$('notifications').textContent=permission==='granted'?'Notifications enabled while connected':`Notifications ${permission}`;});
$('logout').onclick=run(async()=>{saveDraft();await voice.close();await api('/web/logout',{});authenticated=false;ws?.close();clear();location.reload();});$('mic').onclick=run(()=>voice.capture(scope));$('voice-send').onclick=run(async()=>{await voice.send(scope);await refreshConversation();});$('voice-clear').onclick=run(()=>voice.discard());
$('new-task').onclick=run(async()=>{if(newPending){await reconcileStart();return;}$('new-prompt').value=read('newDraft','');$('new-dialog').showModal();const data=await api('/api/projects');$('projects').replaceChildren(...data.projects.map(p=>{const n=el('option');n.value=p.cwd;return n;}));});$('new-prompt').oninput=()=>write('newDraft',$('new-prompt').value);$('cancel-new').onclick=()=>$('new-dialog').close();
async function reconcileStart(){if(startFlight)return startFlight;startFlight=performStart();try{return await startFlight;}finally{startFlight=null;}}
async function performStart(){if(!newPending)return;const p=newPending;let result;try{result=await api(`/api/session-starts/${p.id}`);}catch(e){if(e.status!==404)throw e;try{result=await api('/api/threads',p);}catch(e){if(e.status&&e.status<500){newPending=null;write('newPending',null);}throw e;}}newPending={...p,state:result.state};write('newPending',newPending);renderOutbox();if(result.state==='started'){newPending=null;write('newPending',null);write('newDraft','');$('new-dialog').close();await refreshList();await open(result.thread_id);}else if(['failed','unknown'].includes(result.state)){if(result.state==='failed'){newPending=null;write('newPending',null);}throw Error(result.error||'Task creation uncertain. Check recent work before starting again.');}else $('new-error').textContent='Task accepted. Waiting for the backend to create it…';}
$('new-form').onsubmit=async e=>{e.preventDefault();try{if(!newPending){newPending={id:crypto.randomUUID(),cwd:$('cwd').value,prompt:$('new-prompt').value,permissions:$('permissions').value};write('newPending',newPending);}await reconcileStart();}catch(e){$('new-error').textContent=e.message;}};
$('session-menu').onclick=run(async()=>{$('controls-dialog').showModal();$('watch').textContent=current?.watched?'Unfollow updates':'Follow updates';$('archive').textContent=$('filter').value==='archived'?'Restore':'Archive';const data=await api('/api/models');models=data.models;$('model').replaceChildren(...models.map(m=>{const o=el('option','',m.name);o.value=m.model;return o;}));if(current?.turnSettings?.model)$('model').value=current.turnSettings.model;setEfforts();});
function setEfforts(){const model=models.find(m=>m.model===$('model').value);$('effort').replaceChildren(...(model?.efforts||[]).map(e=>{const o=el('option','',e.reasoningEffort);o.value=e.reasoningEffort;return o;}));$('effort').value=current?.turnSettings?.effort||model?.defaultEffort;}$('model').onchange=setEfforts;
for(const [id,action,body] of [['watch','watch',()=>({enabled:!current?.watched})],['stop','interrupt',()=>({})],['resume','queue/resume',()=>({})],['archive','archive',()=>({})]])$(id).onclick=run(async()=>{await api(`/api/threads/${scope}/${id==='archive'&&$('filter').value==='archived'?'unarchive':action}`,body());$('controls-dialog').close();await refreshConversation();await refreshList();});
$('rename').onclick=run(async()=>{const name=prompt('Session name',current?.thread?.name||'');if(name){await api(`/api/threads/${scope}/rename`,{name});await refreshConversation();await refreshList();}});$('save-turn').onclick=run(async()=>{await api(`/api/threads/${scope}/settings`,{model:$('model').value,effort:$('effort').value,mode:$('turn-mode').value==='plan'?'plan':'default'});$('controls-dialog').close();await refreshConversation();});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').hidden=false;});$('install').onclick=run(async()=>{await installEvent?.prompt();installEvent=null;$('install').hidden=true;});
window.addEventListener('online',()=>{if(authenticated){connectEvents();scheduleRefresh();}});window.addEventListener('offline',()=>{$('connection').textContent='Offline · drafts saved';});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&authenticated){scheduleRefresh();if(ws?.readyState!==WebSocket.OPEN)connectEvents();}});window.addEventListener('pagehide',()=>{saveDraft();void voice.close();});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('search').focus();}if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&innerWidth<=760)document.body.classList.remove('chat-open');});
setInterval(()=>{if(!authenticated||polling||document.visibilityState!=='visible')return;polling=true;void run(async()=>{await refreshConversation();await refreshList();await refreshAttention();if(newPending)await reconcileStart();})().finally(()=>polling=false);},10000);
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
void boot();
